/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MovieDetail_TestNG;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Assert;
import org.testng.annotations.AfterSuite;
import org.testng.annotations.BeforeSuite;
import org.testng.annotations.Test;

import MovieDetail_TestNG.Pages.MovieContents;
import io.github.bonigarcia.wdm.WebDriverManager;

public class MovieDetail_Test {
   static WebDriver driver;
    @BeforeSuite
    public static WebDriver createDriver() {
        
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        return driver;
    }
     
     
    @Test
    public void TestCase01_ImdbMovieContents() throws InterruptedException{
        Boolean status =false;
         MovieContents contents = new MovieContents(driver);
         contents.NavigateToIMDBPage();
         contents.SearchMovieInImdbSite("Pushpa: The Rise");
        status = contents.verifyMovieDetailIMDB("Release date", "January 7, 2022 (United States)", "Country of origin", "India");
        Assert.assertTrue(status,"Failed to fetch and verify the contents of movie");
        
    }
    
    @Test
    public void TestCase02_WikiMovieContents() throws InterruptedException{
        MovieContents contents = new MovieContents(driver);
        contents.NavigateToWikiPage();
        contents.SearchMovieInWikipediaSite("Pushpa: The Rise");
        contents.verifyMovieDetailWiki("Release date", "17 December 2021", "Country", "India");
    }


    @AfterSuite
    public static void QuitDriver(){
        System.out.println("quit()");
        driver.quit();
    }
  
}
